application: mytestcustomtinywebdb
version: 1
runtime: python27
threadsafe: no
api_version: 1

handlers:
- url: /media/images
  static_dir: /media/images
  
- url: /jsclient
  static_dir: jsclient

- url: /robots.txt
  static_files: media/text/robots.txt
  upload: media/text/robots.txt

- url: .*
  script: main.py


libraries:
- name: django
  version: "1.2"
